# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Easy We Chat
subtitle:
description:
author: overtrue
language:
  - zh-cn
  - en
timezone: PRC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://easywechat.org
root: /

permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: easywechat

backers:
    - label: Laravist
      url: https://laravist.com
      img: https://camo.githubusercontent.com/f3d5327bd7dc6a7faeb8a4fbdf3d94e0181e85a5/68747470733a2f2f6f3064706c733172752e716e73736c2e636f6d2f6c617261766973742e636f6d2d6c6f676f2e706e67

swiftype_key: URYXMYgtQuEhNHNY8d-F
google_analytics: UA-64156348-1
github: overtrue/wechat
twitter: anzhengchao
weibo: 44294631